# Generated by Django 4.0.4 on 2022-04-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('idContainer', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('20', '20'), ('40', '40')], max_length=10)),
                ('categoria', models.CharField(choices=[('Exportação', 'Exportação'), ('Importação', 'Importação')], max_length=10)),
                ('status', models.CharField(choices=[('Vazio', 'Vazio'), ('Cheio', 'Cheio')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentos', models.CharField(choices=[('Posicionamento', 'Posicionamento'), ('Descarga', 'Descarga'), ('Gate Saida', 'Gate Saida'), ('Pesagem', 'Pesagem'), ('Gate Entrada', 'Gate Entrada'), ('Scanner', 'Scanner'), ('Reposicionamento', 'Reposicionamento'), ('Embarque', 'Embarque')], max_length=20)),
                ('datacomeco', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora')),
                ('datafim', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora')),
                ('idcontainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cadastro')),
            ],
        ),
    ]
